import 'package:ethnomir/repositories/position/model/position.dart';

List<Position> positions = [
  Position(
    id: '1',
    isActive: true,
    title: 'Шорпа',
    description:
        'Шурпа — заправочный суп или мясной бульон, распространённый в восточной кухне. Как правило, шурпу готовят из баранины, но есть и варианты из говядины или курицы',
    weight: '200',
    caloric: '350',
    price: '390',
    discont: 5,
    establishmentId: '1',
    positionCategoryId: 'Горячее',
    fileId: 'shorpa',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '2',
    isActive: true,
    title: 'Каурма лагман',
    description:
        'Каурма лагман (ковурма лагман) — вариант жареного лагмана из узбекской кухни. Буквально переводится как «поджарка», что означает, что лагман готовится без подливы.',
    weight: '150',
    caloric: '300',
    price: '370',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Горячее',
    fileId: 'lagman',
    isPopular: true,
    isNew: false,
  ),
  Position(
    id: '3',
    isActive: true,
    title: 'Манты с бараниной',
    description:
        'Манты с бараниной — традиционное блюдо многих восточных кухонь, которое славится насыщенным вкусом и ароматом.',
    weight: '300',
    caloric: '350',
    price: '490',
    discont: 15,
    establishmentId: '1',
    positionCategoryId: 'Горячее',
    fileId: 'manty',
    isPopular: false,
    isNew: true,
  ),
  Position(
    id: '4',
    isActive: true,
    title: 'Плов по чайхански',
    description:
        'Плов по-чайхански — повседневный вариант узбекского плова, который готовят каждый день в чайханах. Название связано с старой ташкентской традицией «ош», когда мужчины собираются по четвергам в чайхане «на ош», что означает «на плов».',
    weight: '200',
    caloric: '310',
    price: '420',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Горячее',
    fileId: 'plov',
    isPopular: false,
    isNew: true,
  ),
  Position(
    id: '5',
    isActive: true,
    title: 'Шашлык из баранины',
    description:
        'Плов по-чайхански — повседневный вариант узбекского плова, который готовят каждый день в чайханах. Название связано с старой ташкентской традицией «ош», когда мужчины собираются по четвергам в чайхане «на ош», что означает «на плов».',
    weight: '200',
    caloric: '400',
    price: '700',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Мангал',
    fileId: 'mangal',
    isPopular: false,
    isNew: true,
  ),
  Position(
    id: '6',
    isActive: true,
    title: 'Пицца',
    description: 'Вкусно',
    weight: '200',
    caloric: '400',
    price: '670',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Горячее',
    fileId: 'pizza',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '7',
    isActive: true,
    title: 'Кола',
    description: 'Вкусно',
    weight: '0.3',
    caloric: '30',
    price: '90',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Напитки',
    fileId: 'cola',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '8',
    isActive: true,
    title: 'Фанта',
    description: 'Вкусно',
    weight: '0.3',
    caloric: '30',
    price: '90',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Напитки',
    fileId: 'fanta',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '9',
    isActive: true,
    title: 'Сок Апельсиноый',
    description: 'Вкусно',
    weight: '0.5',
    caloric: '30',
    price: '100',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Напитки',
    fileId: 'apelsin',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '10',
    isActive: true,
    title: 'Сок Яблочный',
    description: 'Вкусно',
    weight: '0.5',
    caloric: '30',
    price: '100',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Напитки',
    fileId: 'apple',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '11',
    isActive: true,
    title: 'Чизкейк',
    description: 'Вкусно',
    weight: '120',
    caloric: '100',
    price: '245',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Десерт',
    fileId: 'cheeze',
    isPopular: false,
    isNew: false,
  ),
  Position(
    id: '12',
    isActive: true,
    title: 'Салат Цезарь',
    description: 'Вкусно',
    weight: '150',
    caloric: '240',
    price: '290',
    discont: 0,
    establishmentId: '1',
    positionCategoryId: 'Салаты',
    fileId: 'salat',
    isPopular: false,
    isNew: false,
  ),
];
