name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web  # Папка со скомпилированными файлами
          # Если вы использовали base href="/my-app/", раскомментируйте:
          # base_path: /my-app/ 